version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: merchant_db
    environment:
      POSTGRES_DB: mms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres.crescue7536
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mms_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./mms_be
      dockerfile: Dockerfile
    container_name: mms_backend
    command: >
      sh -c "
        until pg_isready -h db -p 5432 -U postgres;
        do echo 'Waiting for database...'; sleep 2; done &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    env_file: ./mms_be/.env   # 🔥 backend reads its own env file
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
