# Use postgres/example user/password credentials

services:

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  backend:
    build:
      context: ./mms_be
      dockerfile: Dockerfile
    container_name: merchant_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./mms_be/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./mms_fe
      dockerfile: Dockerfile
    container_name: merchant_frontend
    env_file:
      - ./mms_fe/.env
    ports:
      - "3030:3030"
    depends_on:
      - backend
    restart: unless-stopped
